name: veteran_demographics
version: "1.0.0"
description: "Veteran status from ACS"

sources:
  ncr:
    type: census_acs
    profile: NCR
    years:
      [
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020,
        2021,
        2022,
        2023,
        2024,
      ]
    geographies: [tract, county, block_group]
    variables:
      vet_denom: "B21001_001"
      veteran: "B21001_002"

  va:
    type: census_acs
    profile: VA
    years:
      [
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020,
        2021,
        2022,
        2023,
        2024,
      ]
    geographies: [tract, county]
    variables:
      vet_denom: "B21001_001"
      veteran: "B21001_002"

crosswalks:
  va_county_to_hd: "geographies/VA/State Geographies/Health Districts/2020/data/distribution/va_ct_to_hd_crosswalk.csv"

output:
  path: data/distribution
  standardize: true
